libtool: Add msys bypass path conversion env var LIBTOOL_MSYS_NO_PATH_CONVERSION

diff --git a/build-aux/ltmain.in b/build-aux/ltmain.in
--- a/build-aux/ltmain.in
+++ b/build-aux/ltmain.in
@@ -1028,14 +1028,17 @@ func_cygpath ()
 func_convert_core_msys_to_w32 ()
 {
   $debug_cmd
-
-  # Since MSYS is packaged with cygpath, call cygpath in $PATH; no need
-  # to use LT_CYGPATH in this case.
-  func_convert_core_msys_to_w32_result=`cygpath "$@" 2>/dev/null |
-	$SED -e 's/[ ]*$//' -e "$sed_naive_backslashify"`
-  if test "$?" -ne 0; then
-      # on failure, ensure result is empty
-      func_convert_core_msys_to_w32_result=
+  if [ "$LIBTOOL_MSYS_NO_PATH_CONVERSION" == "1" ]; then
+    func_convert_core_msys_to_w32_result="$1"
+  else
+    # Since MSYS is packaged with cygpath, call cygpath in $PATH; no need
+    # to use LT_CYGPATH in this case.
+    func_convert_core_msys_to_w32_result=`cygpath "$@" 2>/dev/null |
+    $SED -e 's/[ ]*$//' -e "$sed_naive_backslashify"`
+    if test "$?" -ne 0; then
+        # on failure, ensure result is empty
+        func_convert_core_msys_to_w32_result=
+    fi
   fi
 }
 #end: func_convert_core_msys_to_w32
